name: Go CI

on:
  push:
    branches:
      - main # or your default branch
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Run tests in broker
        run: go test ./...
        working-directory: ./broker

      - name: Run tests in control_plane
        run: go test ./...
        working-directory: ./control_plane

      - name: Run tests in indexer
        run: go test ./...
        working-directory: ./indexer

      - name: Run tests in query_understanding
        run: go test ./...
        working-directory: ./query_understanding

      - name: Run tests in searcher
        run: go test ./...
        working-directory: ./searcher
